### ISSUE TITLE
Nothing shows up...

### ISSUE THREAD

**Issue by Raffer807** [AlessandroZ/LaZagne#508] opened 2020-06-13 15:55 UTC
Sorry to bother again but even if I finally finished the installation, I still have a problem; this is what happens when I activate LaZagne in the cmd :
![image](https://user-images.githubusercontent.com/66703713/84573056-82da3d00-ad9e-11ea-9920-3f507a54a7b3.png)
I guess it's not normal, is it? Especially since nothing happens afterwards! I've done this also with other commands, but this is the same thing too, yet I followed everything you told me: after the comments where I said I couldn't do it, I redid everything and rechecked in detail, so normally everything should be good...

**Comment by Papotito123** [comment] 2020-06-13 21:35
Hello:
Seems you mánaged to compile or close.
For compiling time,disabled any antivirus including Defender.
When I compile, the output name is lazagne.exe.I see you have laZagne.exe.The capital Z is used in the .py file.
Try running(as your case)
   laZagne.exe all -vvv

,for verbose output.
If nothing is printout ,then the compiled is bad.
Take a closer peek to the cmd when compiling.
You will see the traceback and with this try to debug.

**Comment by Raffer807** [comment] 2020-06-13 21:56
Thanks @Papotito123 
So first, I recompiled LaZagne without the antivirus activated but unfortunately, nothing changed...
So I did what you asked & here's the result :
![image](https://user-images.githubusercontent.com/66703713/84579815-728f8580-add1-11ea-81aa-6d573b7c0344.png)
As you can see I can't go further since there's an error...

**Comment by Papotito123** [comment] 2020-06-13 23:34
Hello:
Because the full laZagne.py path is not right.
In your case:
  python "C:\Users\Rafael\Desktop\Lazagne-master\Windows\laZagne py"

Then run:
laZagne.py -version
,to get the version number

If you get a version number (maybe 2 4 4), then :
laZagne.py all -vvv

**Comment by Raffer807** [comment] 2020-06-13 23:44
Thanks for the reply^^
Strangely when I typed the command, LaZagne ran normally: 
![image](https://user-images.githubusercontent.com/66703713/84581340-69f27b80-ade0-11ea-8aa0-4cd5b25df226.png)
Can I use the program like this? Or maybe should I try to continue to fix it?

**Comment by Papotito123** [comment] 2020-06-14 04:10
Hello:
Because the names are case sensitive in python.
Well now you can run laZagne.py.

I don't know if is needed,but before compiling I run laZagne .py because there's some files being created (and maybe needed when doing compile). 

What I don't see is the version number .Should be here output.

**Comment by Raffer807** [comment] 2020-06-15 01:13
@Papotito123 Well as I said, when I enter laZagne.py the cmd display it normally BUT I can't run it, each command that I enter don't do something :

> Edit : Well actually I can't lol, each time I enter a command, the cmd says it does not recognize it...

For the version number I don't know again I can't do anything after I enter laZagne.py the cmd block & nothing I enter do something, however, the file have actually the name laZagne.py after being decompressed so I don't see any problem there...

Finally, I downloaded the .zip so I don't think there should be a problem too, do you mean I shouldn't have clicked on this?
![image](https://user-images.githubusercontent.com/66703713/84609166-210cf680-aeb6-11ea-96f4-efc727515046.png)
Thanks in advance ;-)

**Comment by Papotito123** [comment] 2020-06-15 05:39
Hello:
Yes.Download from here.Unzip it.
As for me, I do like this:
Put the extracted folder in C: \  root.
cmd(run as admin) 
then:  cd "path_to_python folder"
then do : 
 pip install -r  "full_path_to_requirements.txt" 
then:  python "full_path_to_laZagne.py"
Then :   "full_path_to_laZagne.py" -version

If still have problems ,you better check your python installation .
I know with confidence that laZagne.py runs well and can be successfully compiled.

**Comment by AlessandroZ** [comment] 2020-06-15 09:24
If you manage to compile but nothing works, you should have missed some windows dependencies. 
Check older issues you should find what you need, lots of person had this problem: 
- https://github.com/AlessandroZ/LaZagne/issues/372
- https://github.com/AlessandroZ/LaZagne/issues/356

**Comment by Raffer807** [comment] 2020-06-15 12:44
@Papotito123 I did exactly the same process except that my unzipped folder was not C:\ but rather on the desktop, I'll try to redo it with the file on the disk though ;-)
@AlessandroZ  Thanks but it's no use, I've already got pywin32 installed:
![image](https://user-images.githubusercontent.com/66703713/84658780-b213ba00-af16-11ea-8ba2-ebb913b44b0a.png)

**Comment by Papotito123** [comment] 2020-06-15 19:19
Hello:
You still didn't used full right path.
 For requirements.txt install(remember to substitute the path between " " with your real path),but need to specify requirements.txt at end of path.

 pip install -r  "C:\Users\Rafael\Desktop\Lazagne-master\requirements.txt"

**Comment by Raffer807** [comment] 2020-06-15 19:27
@Papotito123 thanks but it doesn't seem to work in this case, either :
![image](https://user-images.githubusercontent.com/66703713/84697795-0e92cb80-af4f-11ea-8da8-40e43491ae4f.png)

**Comment by Papotito123** [comment] 2020-06-15 23:25
Hello:
And this is good.
It's telling you that the file requirements.txt is not where you are pointing.

Read this and adjust as your needs:
https://projects.raspberrypi.org/en/projects/using-pip-on-windows/4

But first,please check if python is installed and is a good installation(in the article explain howto)
Also take note of the paths.And set the Environment Variables for your python installation(also,in the article explain howto)

**Comment by Raffer807** [comment] 2020-06-15 23:39
@Papotito123  But the file IS where I'm pointing : 
![image](https://user-images.githubusercontent.com/66703713/84715728-a3a6bc00-af71-11ea-96d9-49230ba0eeee.png)
Also, I'm sure I installed Python correctly, I checked the instructions several times and paid attention to every detail and yes I entered the environment variables, here's what I put:
> C:\Python\Python37;C:\Python\Python37\Scripts;C:\Python\Python37\libs

**Comment by Papotito123** [comment] 2020-06-16 01:33
Hello:
Ok.
This error is:
The python process is looking for file in the directory it is running from.
So,is looking for requirements.txt inside Python37 folder.So,the path for "\..\.requirements.txt" is not interpreted.
See.Whatever command you run is using the cmd running path and not the true path of any file.
Don't use the " " for any path, just for test.
When using pip ,instead use  pip3.7.exe

If problem still,maybe you have some trash for deleted python installation in some temp file or cache.

**Comment by Banaanhangwagen** [comment] 2020-06-16 06:43
@Raffer807 
please check your path! @Papotito123 already mentioned it, but you are still not paying attention
based on your screenshots, I see that you are not pointing to the correct folder/path

if your latest screenshot is still correct, it should be this :
`pip install -r "C:\LaZagne-master\requirements.txt"`

make sure you use tab to autocomplete the path in cmd in order to avoid typos/wrong or non existing paths

**Comment by Raffer807** [comment] 2020-06-16 14:25
@Banaanhangwagen thanks, I'm sorry @Papotito123, I didn't pay attention and actually confused the paths I was supposed to take into the CD! My bad...

**Comment by Papotito123** [comment] 2020-06-16 17:16
Hello:
You are still out of  focus.

cmd   
type:
cd "full path to python folder"
* please stay always in python folder,don't move out *

pip install -r "full path to \requirements.txt"

python "full path to \laZagne.py"

"full path to \laZagne.py" -version

"full path to \laZagne.py" all

If cmd is  not in python folder path this will fail.keep this in mind.
And about compiling,you need some to perform this.
So,keep focus in first stage: have a good python install , successfully run laZagne.py , and got good results.

I had very hard time when starting to do this because didn't anything about python.I had a very painful time(@AlessandroZ , @MyLoginOnGitHub , and others know it)
But I was proactive trying to learn.
And most of all, I already know CMD basic stuff.
And I suspect that's your issue. 
If you don't know where you are and how to move., you will be straightforward to an error.
Maybe you have a python installation but you are not using it.

Take some breath.Focus in what you want. 
Read some about cmd basics.

Then try what I suggest to do 
But take some reading.
Trying to do this concept of python without knowing cmd basics will give you more headaches. 

And always keep a 1% of the benefit of doubt but against you.This will turn on the desired to check if you are wrong.

If I did it, also you can.

**Comment by Raffer807** [comment] 2020-06-16 18:04
@Papotito123  Thanks for the support^^

> If cmd is not in python folder path this will fail.keep this in mind.
What do you mean exactly by this? I don't really understand tbh...

> Maybe you have a python installation but you are not using it.
Hmm, I don't really understand what you are trying to point out but I guess it's about the installation of Python right? Well then I suppose it should not really be a problem since I proceeded as you and @AlessandroZ indicated but I can start all over again from the beginning if you want ;-)

**Comment by Papotito123** [comment] 2020-06-17 01:48
Hello:
You are not making things easy for you.

First of all. You need to be sure you have a good python installation.

Download lazagne latest code from green button(at right) : https://github.com/AlessandroZ/LaZagne

Extract it . 
Copy the whole extracted folder to C:\ root. (you should had some like this:  C:\LaZagne-master\LaZagne-master )

Now take a look at this screenshots.(Look closely)
In  the screenshots,  my lazagne path is   C:\lazagnee  , because this is my latest lazagne run(and I want to give it a name) 
.But this should not be issue for you because you have to adjust as your needs.
So just copy the whole folder to C:\

![Pythoncheck+requirements](https://user-images.githubusercontent.com/53058383/84844270-fcc92b00-b017-11ea-8ee3-f56753a03402.jpg)

![laZagne py+version](https://user-images.githubusercontent.com/53058383/84844285-06eb2980-b018-11ea-9113-24a2a3f2fb0b.jpg)

![laZagne py all](https://user-images.githubusercontent.com/53058383/84844306-0eaace00-b018-11ea-8b6f-f3c53290939f.jpg)

After looking this, try to run each command starting with the firs:,  python 

As you see in screenshot I have Python 3.7.6  64 bit (AMD64) installed.
That's what you need to see at first(maybe you have Python 3.7.x , where x is another build number,but is not issue.Its just you have a  another build)

And take your time.

**Comment by Raffer807** [comment] 2020-06-17 15:03
Well @Papotito123 I reinstalled laZagne & Python & followed what you did (I guess?) on your screenshot, but it doesn't work, here's what I did compared to you
![image](https://user-images.githubusercontent.com/66703713/84912644-ed022300-b0b9-11ea-9b89-f2ceb88a7fe0.png)
This is what happens at the beginning of your first screenshot, at first, everything works perfectly... but after :  
![image](https://user-images.githubusercontent.com/66703713/84914687-2d62a080-b0bc-11ea-87ed-e70b2deca78a.png)
This is what happens when you enter _"C:\LaZagne-master\Windows\laZagne.py" -version_
![image](https://user-images.githubusercontent.com/66703713/84912899-32beeb80-b0ba-11ea-9ba8-7d5b4c37ad4a.png)
& this is what happens when I enter it...

Any idea of why such a difference?

**Comment by Papotito123** [comment] 2020-06-17 17:27
Hello:
The good news is seems you have python installed.Also managed to install requirements.txt well
And you did right in this last effort.
Paths and command looks good.

In Environment Variables, did you set:
     C:\Python\Python37\python.exe
?

Important,when downloading a file ,in this case should be lazagne.zip,I do right-click and untick the option Unblock or press Unblock.(not doing can limit file capabilities).
And then extract/unzip the file.

One issue I had when attempting to compile was files kept in some temp/cache folders after uninstalling/reinstalling.
Could looks like even all things seems good, something wrong from your firsts attempts is still in OS.

And that's the painful part(because I've therewhen start to "trying compiling" without knowing Python.
When things looks good but doesn't works as should be and we start to redoing without knowing what was did good and what not.

Look in windows temp.

**Comment by Papotito123** [comment] 2020-06-17 17:35
Hello:
Do this as a test.
This is firefox password grabber(it collaborate with lazagne).
Do download as same as with lazagne.
Install its requirements.txt as with lazagne(should say requirements are satisfied because are in common with lazagne).
And run firepwd.py as you do with lazagne.
Of course, if you doesnt have a password saved in Firefox will not print any but the tool will run.

If you can't run this, is more like some older python still in your system .

You are moving to right track.
But this looks like a tiny detail harder to find.

**Comment by Raffer807** [comment] 2020-06-17 21:25
@Papotito123 so I did the test but, I didn't look like it was working, the cmd displayed this : 
![image](https://user-images.githubusercontent.com/66703713/84951953-7bde6200-b0f1-11ea-82c5-7b88d0c614af.png)
Does that mean that there are some remnants of my older installation? Or maybe I did something wrong when I entered the commands?

**Comment by Papotito123** [comment] 2020-06-17 22:15
Hello:
As I look closely to your screenshots seems you have Windiws 7 installed.

If you doesnt have Firefox with a saved login,will not find key3.db/key4.db .
But the tool runs.
So for your benefit,try to find a simple .py script(that do something easy) and try to run .To be really sure python is doing good 

Regarding python.exe ,just add the full path to Environment Variables.

Another tip to do,because maybe s needed:

cmd > cd "python folder"
pip3.7 install --update setuptools

--update , is using  2 dashes ( - )

Try this, copy all this below and save as osname.py :

import os, platform
print("Operating system name:")
print(os.name)
print("Platform name:")
print(platform.system())
print("Platform release:")
print(platform.release())

,and run as you should know.
This will output Os name, architecture. No harm to OS.

**Comment by Raffer807** [comment] 2020-06-18 00:27
@Papotito123  I didn't understand this : 

> cmd > cd "python folder"
> pip3.7 install --update setuptools
> 
> --update , is using 2 dashes ( - )
> 
> Try this, copy all this below and save as osname.py :
> 
> import os, platform
> print("Operating system name:")
> print(os.name)
> print("Platform name:")
> print(platform.system())
> print("Platform release:")
> print(platform.release())

Please, can you be more precise on what should I do? Also when I enter _pip3.7 install --update setuptools_ the cmd says that : _no such option: --update_...

**Comment by Papotito123** [comment] 2020-06-18 00:47
Hello:
The command should be:
     pip3.7 install --upgrade setuptools

Then,download this file, Is the script that I mention before.I did it for you.
Just rename it to osname.py.This github Upload doesn't let attach .py files.

[osname.py.txt](https://github.com/AlessandroZ/LaZagne/files/4795670/osname.py.txt)

And run as you should know, how to run a .py script.This will no need any requirements.txt  installation.

This will output Os name, architecture. No harm to OS.

**Comment by Raffer807** [comment] 2020-06-18 10:54
@Papotito123 I did it : 
![image](https://user-images.githubusercontent.com/66703713/85012158-e67bb600-b162-11ea-8f0d-106f2d4d760e.png)

**Comment by Papotito123** [comment] 2020-06-18 16:40
Hello:
Now run laZagne.py as you should know.

Why I make folder with name (as laza, lazo, and others) instead using the default name ?
Because if you have more than 1 lazagne at a time and you get issues ,is more easy to track from where went.
If you have some file stuck in OS /registry even you do things right , you will still get fail.But is more easy when having the path of a running file.

Also until you get more experience running lazagne, please run always with   -vvv.  .
The traceback will be of help. 

   python "path of laZagne.py" 
   "path of laZagne.py" -version
   "path of laZagne.py" all -vvv

**Comment by Papotito123** [comment] 2020-06-18 23:09
Hello:.
Did you run this?:
      "path of laZagne.py" all -vvv

This could be of help.

**Comment by Raffer807** [comment] 2020-06-18 23:19
Should I run before or after I entered _"path of laZagne.py" -version_ though?

**Comment by Papotito123** [comment] 2020-06-18 23:32
Hello:
Is good and is bad.
Good because do the same.
Bad because didn't give a clue.
So the issue is related to laZagne.py needed packages in python.
There should be some of the first time you run it ,that were not the indicated in requirements.txt 

Apart from running requirements.txt, did you install any package manually in python?
You know, like install pypykatz / cryptodome / or other manually?

**Comment by Raffer807** [comment] 2020-06-18 23:37
Well if by manually you mean I entered some functions in the cmd to install them then yes since it's what's AlessandroZ (I guess?) indicated for installing LaZagne...

**Comment by Papotito123** [comment] 2020-06-18 23:55
Hello:.
Ok.Read again.
Apart from running requirements.txt, did you install any package(that is mention in requirements.txt,) manually in python?
We are mention that let requirements.txt install the needed packages.
So straight , did you manually install pypykatz / pycryptodome /  rsa / enum34 / pyasn1 in python?
pycryptodome can cause issues having more than 1 version.
Also,the very first time any of this packages are installed (doesn't matter if were from requirements.txt or installed manually) a copy of each package is kept in a cache folder for when needed.So python use this  first instead of other.If the cached file is wrong or bad, you will get stuck with it.

You need to seek some readings about install and uninstall packages in python,about cleaning python packages that are cached and you want to clean,and how to safely clean temp files.

**Comment by Papotito123** [comment] 2020-06-19 02:22
Hello:
Just a question for any of @AlessandroZ , @MyLoginOnGitHub:
 ,this guy has Windows 7 x64 and Python 3.7.0 x64 - there's any problem for running laZagne.py ?

So much thanks.

**Comment by Papotito123** [comment] 2020-06-19 02:34
Hello:
@Raffer807 , you are sure you didn't install pypykatz wheel version ?, and maybe other packages ?.
I see pypykatz wheel in one of your screenshots.
For me, this caused trouble.
Uninstall any pypykatz / pycryptodome / rsa / enum34 / pyasn1 and delete any copy is cached.
Then verify if there's any of this installed
Then,  run requirements.txt.

Also in the before post,I did a question to @AlessandroZ , @MyLoginOnGitHub  for your clarification and benefit.
Seek for the answer to be post.

**Comment by Raffer807** [comment] 2020-06-19 13:34
@Papotito123  Thanks again for your support Papotito^^, I'll take a look however, do you have the link? I don't know which post is involved...

Concerning the packages idk, I guess I'll reinstall Python then, I prefer to take no risks, then I'll let you know ;-)

**Comment by AlessandroZ** [comment] 2020-06-19 13:54
@Papotito123 no I don't think the problem is related to the OS or the python version. Never heard about a problem like that. 

@Raffer807 try:

```
cd C:\LaZagne-master\Windows
C:\Python\Python37\python.exe LaZagne.py all 
```

**Comment by Raffer807** [comment] 2020-06-20 00:54
@Papotito123  I reinstalled Python but I don't know how to check the packages though...
@AlessandroZ Thanks! It actually worked! However the program didn't show me all the passwords, it says that I must try again with the -v option :
![image](https://user-images.githubusercontent.com/66703713/85187622-1c26b900-b2a1-11ea-8712-c8c57fcbef1a.png)
Which command do I need to enter to get it to show me the remaining passwords?

**Comment by Papotito123** [comment] 2020-06-20 01:42
Hello:
Running as @AlessandroZ suggestion means python.exe is not set But you have a workaround 

lazagne shows passwords related to the logged user ,and no other accounts.
Chrome logins are recovered if they were Saved .

With debugging:

   cd C:\LaZagne-master\Windows
 C:\Python\Python37\python.exe LaZagne.py all -v

**Comment by Raffer807** [comment] 2020-06-20 17:20
@Papotito123  so I entered the commands but it still says that 7 other passwords have been found without showing them : 
![image](https://user-images.githubusercontent.com/66703713/85207727-1aa1d300-b32b-11ea-8939-2895476f3ef7.png)

**Comment by Papotito123** [comment] 2020-06-21 01:28
Hello:
If said 7 passwords,means that 7 passwords were recovered(including duplicated).

I assure that for Chrome 80 and new(also older logins) and for Firefox 75 and new , lazagne is at is best in latest git code.
From nirsoft:
Be aware that IE10/IE11 under Windows 7 doesn't use the Windows Vault to store passwords.

**Comment by Raffer807** [comment] 2020-06-22 00:23
@Papotito123  Sorry but I don't really understand your point, does that mean that I can't ultimately recover this 7 passwords?

**Comment by Papotito123** [comment] 2020-06-22 04:24
Hello:
It's easy to understand.
It says found 7 passwords.Well between all modules ran,it grabs passwords (some in plain-trext ,other in hexadecimal and maybe some in python bytes.).
The passwords are here in the cmd.

So you want to see the passwords printed,then run :

cd C:\LaZagne-master\Windows

C:\Python\Python37\python.exe LaZagne.py all -oA -output "C:\LaZagne-master"

**Comment by Raffer807** [comment] 2020-06-22 04:32
@Papotito123 Wait...do you mean that when it says "7 passwords have been found" it's just the total number of passwords it already found rather than 7 more passwords? So basically it already showed me all the passwords it found?

**Comment by AlessandroZ** [comment] 2020-06-22 09:21
For me the issue is closed. 

@Papotito123 has been really nice and really patient with you, I think this issue is the longest issue I have ever seen :) 

Now @Raffer807 please, do not ask every questions you have. You should do some research first to understand how things work. All your questions have been already answered on older issues. Try to understand how credentials are retrieved to understand why yours are not, etc.

**Closed by AlessandroZ** 2020-06-22 09:21 UTC

**Comment by Raffer807** [comment] 2020-06-22 11:17
@AlessandroZ  @Papotito123  Well I guess you're right, I feel I might have bothered you with my lack of understanding but I guess I should have been more focused lol, apologize if it's the case.

I didn't find my password but at least I could successfully have run LaZagne thanks to you two so thanks a lot for that & to have supported my questions ;-)
