### ISSUE TITLE
2.3 still not working with russian characters

### ISSUE THREAD

**Issue by hubsternonangry** [AlessandroZ/LaZagne#154] opened 2017-10-09 05:25 UTC
I have more than 250 passwords, saved in chrome, but LaZagne no one cant extract.
And, no one paswword for Wi-Fi, but there is no cyryllic symbols, english only.

// Some passwords results was changed before I posted this. 

```
C:\Users\Виктория>D:\001\laZagne.exe all

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

########## User: ┬шъЄюЁш  ##########

------------------- Skype passwords -----------------

Hash found !!!
Login: god
Hash: 21e6fe41042add5ebcc
shema to bruteforce using md5: god\nskyper\n<password>

Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\browsers\chrome.py", line 50, in run
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7: ordinal not in range(128)

------------------- Credential manager passwords -----------------

Password found !!!
URL: Microsoft_PaidConnectivity_WiFi_AccessToken
Login: None
Password: ╨МЭ▀╤Мz└O┬Ч▓3
ыs╤м═┴$з
Й╕л╬╪~e╝viO╞▀Mrg╩Oл3Пй■╗ ▄╬Rоcў<╙ц.уЪЬK┤╖1╨"░ADGчКK0Эg╞5\│╦─╓■■И█Р№│З <~╪вё@C_ўвЖрЯ$└¤ЪqЫ8▐вk▄хCрSZ▄r!1Вb┤}=Я.╫~dє∙√В"┘Ї!

------------------- Vault passwords -----------------

Password not found !!!
URL: MicrosoftAccount:target=SSO_POP_Device
Username: 02krevsevfki


[+] 2 passwords have been found.
For more information launch it again with the -v option


elapsed time = 2.09300017357
```

**Comment by AlessandroZ** [comment] 2017-10-09 13:13
As I told you, the output printed could not be correct because it depends on your system encoding. However, it should work, if you write the output on a text file. 

`lazagne.exe all -oA `

I have tested with Russian chars and it worked.

**Comment by AlessandroZ** [comment] 2017-10-09 13:15
For wifi passwords, run Lazagne as administrator. 
For Chrome, I need more information. Try using the verbose output: 
`Lazagne.exe browsers -vvv`

**Comment by hubsternonangry** [comment] 2017-10-09 15:17
Trying to `Lazagne.exe browsers -vvv` run as administrator
Im sure I use Google Chrome browser and it is not portable version. It is installed on C:\Program Files (x86)
```
D:\001>lazagne.exe browsers -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|

[ERROR] error encoding: 'ascii' codec can't decode byte 0xc2 in position 17: ordinal not in range(128)

########## User: ┬шъЄюЁш  ##########

 ------------------- Chrome passwords -----------------


Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\browsers\chrome.py", line 50, in run
  File "ntpath.py", line 85, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7: ordinal not in range(128)

 ------------------- Coccoc passwords -----------------


[INFO] Cococ not installed.

[!] No passwords found

 ------------------- Opera passwords -----------------


[INFO] Opera is not installed.

[!] No passwords found

 ------------------- Firefox passwords -----------------


[INFO] Profile path found: C:\Users\┬шъЄюЁш \AppData\Roaming\Mozilla\Firefox\Profiles/6e6k6qjc.default

[!] No passwords found

 ------------------- Internet explorer passwords -----------------


[INFO] Internet Explorer passwords are stored in Vault (check vault module)

[!] No passwords found

laZagne.py:273: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
[ERROR] error encoding: 'charmap' codec can't encode characters in position 17-24: character maps to <undefined>

########## User: Виктория ##########


[INFO] Using PID: 5416

 ------------------- Chrome passwords -----------------


[INFO] Google Chrome not installed.

[!] No passwords found

 ------------------- Coccoc passwords -----------------


[INFO] Cococ not installed.

[!] No passwords found

 ------------------- Opera passwords -----------------


[INFO] Opera is not installed.

[!] No passwords found

 ------------------- Firefox passwords -----------------


Traceback (most recent call last):
  File "laZagne.py", line 127, in launch_module
  File "lazagne\softwares\browsers\mozilla.py", line 434, in run
  File "lazagne\softwares\browsers\mozilla.py", line 114, in get_path
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-16: ordinal not in range(128)

laZagne.py:214: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
########## User: &#1042;&#1080;&#1082;&#1090;&#1086;&#1088;&#1080;&#1103; ##########

 ------------------- Firefox passwords -----------------


[INFO] Firefox not installed.

[!] No passwords found

########## User: DWM-1 ##########

 ------------------- Firefox passwords -----------------


[INFO] Profile path found: C:\Users\DWM-1\AppData\Roaming\\Mozilla\Firefox\Profiles/6e6k6qjc.default

[!] No passwords found

[ERROR] error encoding: 'ascii' codec can't decode byte 0xc0 in position 17: ordinal not in range(128)

########## User: └фьшэшёЄЁрЄюЁ ##########

 ------------------- Firefox passwords -----------------


[INFO] Firefox not installed.

[!] No passwords found

[ERROR] error encoding: 'ascii' codec can't decode byte 0xc2 in position 17: ordinal not in range(128)

########## User: ┬ёх яюы№чютрЄхыш ##########

 ------------------- Firefox passwords -----------------


[INFO] Firefox not installed.

[!] No passwords found


[+] 0 passwords have been found.


elapsed time = 0.552999973297

```

**Comment by hubsternonangry** [comment] 2017-10-09 15:25
Running `lazagne.exe all -oA` creates a folder with file credentials but no one password iside.
It contans this only:
```

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
		
- Date: 2017-10-09 15:22:24
- Username: Виктор
- Hostname:DESKTOP-1LVWFHE


[+] 2 passwords have been found.


```

**Comment by AlessandroZ** [comment] 2017-10-12 09:08
Ok I think the problem is more complex than I thought. I tried with russian characters and it worked. However, your errors occurred before to retrieve the passwords. I suppose because the path is in Russian and not ascii (I didn't try this case). 
Let me some time and when I could have more time, I will come back to you with I hope a solution (right now, I cannot work on it so it could take some time). 

Have a nice day.

**Comment by AlessandroZ** [comment] 2017-10-18 13:33
It should be fixed, could you please try this version: https://github.com/AlessandroZ/LaZagne/releases/tag/2.3.1

Thanks

**Closed** 2017-11-02 15:05 UTC

**Comment by Sourabh002** [comment] 2018-03-10 12:02
It's not working on windows 10 after January 2018 windows update.

**Comment by Drakon5999** [comment] 2018-05-04 16:16
> It should be fixed, could you please try this version: https://github.com/AlessandroZ/LaZagne/releases/tag/2.3.1

It dont work for me. :(
```
C:\Users\Администратор\Desktop\Новая папка>laZagne.exe all -vvv

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
 
[ERROR] error encoding: 'ascii' codec can't decode byte 0xc0 in position 17: ordinal not in range(128)
 
########## User: └фьшэшёЄЁрЄюЁ ##########
 
Traceback (most recent call last):
  File "laZagne.py", line 423, in <module>
  File "laZagne.py", line 267, in runLaZagne
  File "laZagne.py", line 226, in set_env_variables
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)
[8352] Failed to execute script laZagne
```
@AlessandroZ
