### ISSUE TITLE
ERRO in Windows Secrets passwords

### ISSUE THREAD

**Issue by glira** [AlessandroZ/LaZagne#50] opened 2015-10-03 02:51 UTC
when I run with "all" I get this message
```
------------------- Windows Secrets passwords -----------------

Traceback (most recent call last):
  File "<string>", line 190, in <module>
  File "<string>", line 116, in runAllModules
  File "<string>", line 75, in launch_module
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\softwares.windows.secrets", line 50, in run
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\subprocess", line 702, in __init__
  File "C:\Users\John\Desktop\build\laZagne\out00-PYZ.pyz\subprocess", line 823, in _get_handles
WindowsError: [Error 6] Identificador inválido
```
I believe this error is simple to resolve, at least not stop the execution and continue with the other modules.

**Comment by AlessandroZ** [comment] 2015-10-04 20:46
It has been fix in the version 1.0
Thanks

Open the issue again if you still have problems

**Comment by marcelomaia** [comment] 2016-04-19 18:27
how did you solve this? i have the same problem

**Comment by AlessandroZ** [comment] 2016-04-21 15:19
I will check when I will have more time. I thought it was fixed. I cannot reproduce the error so I trying to fix it without to be sure.

**Comment by AlessandroZ** [comment] 2016-07-02 13:30
I added a new try / except in order to not print this stacktrace and continue the execution. I cannot reproduce this error so it's difficult to correct it. I will close this issue.

**Closed by AlessandroZ** 2016-07-02 13:30 UTC
Labels: cannot reproduce

**Comment by marcelomaia** [comment] 2016-07-05 11:25
OK! thank you very much!
