### ISSUE TITLE
error encoding: 'ascii' codec can't decode byte 0xc1 in position 10: ordinal not in range(128) in wifi direct

### ISSUE THREAD

**Issue by eranzim** [AlessandroZ/LaZagne#256] opened 2018-07-31 14:11 UTC
I ran the code (with "wifi -v" params) from PyCharm running as system. It found my wifi passwords, including my [WiFi direct](https://en.wikipedia.org/wiki/Wi-Fi_Direct) password (a binary string), however it also gave an error. I'm assuming this is why when I run it from cmd it just says that no password was found (I admit I don't fully understand why there is a difference between running from cmd or from PyCharm, but let's put that aside for the moment). I would expect a binary representation of the password to be displayed (e.g.: repr, or see what gentilkiwi did in mimikatz), but instead I get something like this:
```
[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: DIRECT-zGMYHOSTNAMELPPF
[-] error encoding: 'ascii' codec can't decode byte 0xc1 in position 10: ordinal not in range(128)
Password: ��gT�
NȃѲ��F4,���g��|@<ٵ�f
```

**Comment by eranzim** [comment] 2018-08-01 11:05
It's from the DPAPI method. If I'm not mistaken, the first time I reproduced it, I got the stack trace in the original post in https://github.com/AlessandroZ/LaZagne/issues/242 (and I am running it with system privileges, and netsh prints Profile "..." is not found on the system).

I put an exception breakpoint and got this stack trace:
```
Stack: 
	try_unicode, write_output.py:88
	do_print, write_output.py:99
	print_output, write_output.py:244
	run_module, laZagne.py:96
	launch_module, laZagne.py:141
	runModule, laZagne.py:159
	runLaZagne, laZagne.py:307
	<module>, laZagne.py:440
	run, pydevd.py:1068
	main, pydevd.py:1658
	<module>, pydevd.py:1664
```

If you need anything else - let me know :)

**Comment by AlessandroZ** [comment] 2018-08-01 11:29
If you have wifi passwords, you should retrieve it using netsh so it's weird that you not see it. 
So you confirm that this line do not print you the password in clear text: 
`netsh wlan show profiles name=DIRECT-zGMYHOSTNAMELPPF key=clear`

If not, I don't know what's happening. 

For DPAPI, try running lazagne with -vvv enabled to print all debug output, you should have [this line](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/DPAPI/masterkey.py#L340) printed.

**Comment by eranzim** [comment] 2018-08-01 12:53
I confirm I can't see it with netsh. I can see the other SSIDs. Also, when I just run `netsh wlan show profiles`, I can see a list of all SSIDs **except** for wifi direct. This is true in normal cmd, elevated cmd and system cmd.

I ran it with -vvv. I got the line you marked 12 times, and then 3 times the following:
```
[!] Unable to find MK for blob c4f8...-...-...-...-...5c35
[!] [!] Try using netsh method
```

Bottom line, I believe this is caused because there is a "WiFi" with a binary password, and calling `unicode()` on it (see the stack trace I sent) raises an exception. You should catch this exception and return a unicode of an escaped string. You could go with something like safe_unicode from [here](http://code.activestate.com/recipes/466341-guaranteed-conversion-to-unicode-or-byte-string/), but I would probably do something like `obj = u"HEX[{}]".format(obj.encode('hex'))` (only if a UnicodeDecodeError is caught)

**Comment by AlessandroZ** [comment] 2018-08-01 14:09
Hmm, it's hard to debug like that. 

I cannot be sure that the problem is only a string encoding. I need the entire output of lazagne with -vvv. 
`lazagne.exe wifi -vvv`

I don't know if the system master password has been retrieved (without it, no wifi password can be found).

I need to know if there is a keyMaterial tag containing the encypted blob on the xml file (as I explained you above). I also need to understand [where the password](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/softwares/wifi/wifi.py#L76) has been retrieved before to be printed (from self.decrypt_using_lsa_secret or from self.decrypt_using_netsh). Print the result, if it's from netsh and you do not see the password doing `netsh wlan show profiles name=DIRECT-zGMYHOSTNAMELPPF key=clear`, this means it's a false positive. Try to run this command and looking for 'key content' string, etc. 

It's not only hiding the issue, it's about trying a way to resolve it.

**Comment by eranzim** [comment] 2018-08-02 09:32
I went to the `Microsoft\Wlansvc\Profiles\Interfaces` directory. There are 2 subdirectories there (both with a GUID for a name): the first contains all 3 "regular" WiFi interfaces saved on my machine. The second contains the WiFi direct. In it, the first name tag (under WLANAPProfile) is "WFD_GROUP_OWNER_PROFILE", the second one (under SSIDConfig > SSID) is DIRECT-zGMYHOSTNAMELPPF. In the "regular" WiFi xml files, both name tags have the same value (the SSID).

When debugging the wifi module, I see that it found the file and succeeded at decrypting the key with `decrypt_using_lsa_secret` (`decrypt_using_netsh` was not called). The value returned from `decrypt_using_lsa_secret` is indeed the same binary password that is later printed out in the output.

Of course I also want to solve the issue and not just cover it up, but the evidence does point at it being an encoding issue.. It's also possible you could recreate this issue on your side if you change your WiFi password to have unicode characters and then tell your Windows to remember it, and run LaZagne. I didn't try it, but it sounds like it might also give the same issue.

Here is the entire output (I changed/censored SSIDs, passwords and GUIDs, for privacy reasons):
```
C:\Python27x64\python.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 58383 --file C:/Code/Plexus/contrib/LaZagne/Windows/laZagne.py wifi -vvv
pydev debugger: process 19364 is connecting

Connected to pydev debugger (build 181.4892.64)

|====================================================================|
|                                                                    |
|                        The LaZagne Project                         |
|                                                                    |
|                          ! BANG BANG !                             |
|                                                                    |
|====================================================================|
		
########## User: UMFD-1 ##########


[!] Using PID: 1292
 ------------------- Wifi passwords -----------------

[!] [+] System masterkey decrypted for ...fe3a
[!] [+] System masterkey decrypted for ...8261
[!] [+] System masterkey decrypted for ...983a
[!] [+] System masterkey decrypted for ...bec2
[!] [+] System masterkey decrypted for ...5c35
[!] [+] System masterkey decrypted for ...c745
[!] [+] System masterkey decrypted for ...fe3a
[!] [+] System masterkey decrypted for ...8261
[!] [+] System masterkey decrypted for ...983a
[!] [+] System masterkey decrypted for ...bec2
[!] [+] System masterkey decrypted for ...5c35
[!] [+] System masterkey decrypted for ...c745
[!] Unable to find MK for blob ...5c35
[!] [!] Try using netsh method
[!] Unable to find MK for blob ...5c35
[!] [!] Try using netsh method
[!] Unable to find MK for blob ...5c35
[!] [!] Try using netsh method
[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: E...
Password: XXX

[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: DIRECT-zGMYHOSTNAMELPPF
[-] error encoding: 'ascii' codec can't decode byte 0xc1 in position 10: ordinal not in range(128)
Password: ���gT�
NȃѲ��F�4,����g��|@<ٵ�f

[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: ...
Password: YYY

[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: S...
Password: ZZZ

########## User: UMFD-0 ##########


[!] Using PID: 1140
 ------------------- Wifi passwords -----------------

[!] No passwords found

########## User: root ##########


[!] Using PID: 4880
 ------------------- Wifi passwords -----------------

[!] No passwords found

########## User: DWM-1 ##########


[!] Using PID: 1744
 ------------------- Wifi passwords -----------------

[!] No passwords found

########## User: SYSTEM ##########

[!] Temporary file removed: c:\windows\temp\rrkaufrg
[!] Temporary file removed: c:\windows\temp\jihbvi
[!] Temporary file removed: c:\windows\temp\wchsqsxs

[+] 4 passwords have been found.

elapsed time = 4.29700016975

Process finished with exit code 0

```

**Comment by AlessandroZ** [comment] 2018-08-02 12:35
Thank you for the output. 

You were right, everything works well, the problem is that the password is a binary password (so I suppose the password has not been entered by a human). 
The correction is not easy, because I try to encode the password before printing it, but here it [failed](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/write_output.py#L111), then I [print](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/write_output.py#L113) the result without doing anything and if it fails it prints the repr() version. But it does not fail so the binary version is printed. I cannot know if the password is readable or not. There is no error to catch. 

Thanks to your output, I noticed other problem. "System masterkey" should be decrypted only once, I need to change that as well. 
And I see that temporary files are well removed because you [said](https://github.com/AlessandroZ/LaZagne/issues/246) that these files were still there. I think, the deletion is not done when the tool does not end correctly (I will try to change that too).

**Comment by eranzim** [comment] 2018-08-02 15:04
Indeed, the password wasn't entered by a human (I'm pretty sure it's generated by the OS).
Regarding this failure - it fails in try_unicode, and then indeed reaches the line you specified and fails there again. You can do one of 2 things in my opinion:

1. Fix `try_unicode` - handle `UnicodeDecodeError` by encoding it differently (e.g. hex). It's on its way to get printed anyways.
1. Fix `print_without_error` - in the except block, don't `print_debug` and don't `print message`, but only `print repr(message)` (or another encoding such as hex). Because printing a message when it has unprintable characters won't help the user getting this data..

There is something else though - `message` here already contains the 'Password: ' prefix. That part shouldn't be encoded with the rest.. Either split it here or make the message that comes contain only the password (or have an earlier `encode_password` function, called before formatting the password into the "Password: %s" format).

Regarding the temporary files - they are indeed deleted in this flow, must've been a different flow, probably in a bad flow like you suggested. They should be deleted in a `finally` block, so that it works even if LaZagne was stopped during its run.

**Comment by AlessandroZ** [comment] 2018-09-02 20:40
I will close the issue, try the last version.

**Closed by AlessandroZ** 2018-09-02 20:40 UTC

**Comment by eranzim** [comment] 2018-09-04 09:15
@AlessandroZ I tried again with the newest version. When running from cmd (tried normal cmd, elevated cmd and system cmd), I get:
```
[-] Password not found !!!
INFO: [!] Password not found.
Authentication: WPA2PSK
Protected: true
SSID: DIRECT-zGMYHOSTNAMELPPF
```

But when running from PyCharm again, I see something like this:
```
[+] Password found !!!
Authentication: WPA2PSK
Protected: true
SSID: DIRECT-zGMYHOSTNAMELPPF
Password: ÁëmKà
GÈƒÑ²­ûT0,æ˜–e£Æ|#>ÙµÜp
```

I think both aren't exactly good.. It definitely **should** show the password was found, but show it in some human-readable format, e.g. E3 44 A0 C1 5C...

**Comment by eranzim** [comment] 2018-09-04 10:51
Update: This behavior is true for 32-bit python. In 64-bit python, it is printed to the screen encoded. So the bug is only with 32-bit python.
