### ISSUE TITLE
Invalid prototype

### ISSUE THREAD

**Issue by alxchk** [AlessandroZ/LaZagne#198] opened 2018-02-02 21:15 UTC
https://github.com/AlessandroZ/LaZagne/blob/201822bc0719fbbfebfff779647a312dbc4f055f/Windows/lazagne/config/WinStructure.py#L299

https://msdn.microsoft.com/en-us/library/windows/desktop/ms683180%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

This is C prototype, void means nothing.

**Comment by alxchk** [comment] 2018-02-02 21:22
Also it's bad idea to patch argtypes directly in wintypes.
Because it creates conflict with other modules.

Example:
```
>>> windll.advapi32.LookupPrivilegeValueA.argtypes
[<class 'ctypes.c_char_p'>, <class 'ctypes.c_char_p'>, <class 'lazagne.config.WinStructure.LP_LUID'>]
```

In this case LP_LUID definition is local to lazagne, and other module will get error if lazagne will be loaded after them.

**Comment by AlessandroZ** [comment] 2018-02-02 21:52
For me it was the good way to define prototypes using ctypes. I understand what you said but I don't know another way without using argtypes. If you have an idea, let me know.

**Comment by alxchk** [comment] 2018-02-02 22:03
Simplest way to use ctypes.XXX.LoadLibrary directly. In this case new "context" will be created. So argtypes specified for this object will be visible only by that object.

**Comment by AlessandroZ** [comment] 2018-02-14 17:27
Hi, 

How did you get this output:
```
>>> windll.advapi32.LookupPrivilegeValueA.argtypes
[<class 'ctypes.c_char_p'>, <class 'ctypes.c_char_p'>, <class 'lazagne.config.WinStructure.LP_LUID'>]
```

Doing `python -i lazagne.py`, I cannot reproduce it. Did you do it using pupy ?

**Comment by alxchk** [comment] 2018-02-14 20:19
Yes, last statement is correct ^^
Because of that it also conflicts with other module

**Comment by AlessandroZ** [comment] 2018-02-15 14:16
I didn't manage to reproduce your output using pupy but I have understood the problem. It should be fixed  doing [this](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/WinStructure.py#L261). 
I also discovered that I don't use anymore GetCurrentProcessId so I removed it. I used instead [os.getpid](https://github.com/AlessandroZ/LaZagne/blob/master/Windows/lazagne/config/changePrivileges.py#L33). 

Do not hesitate to open the issue again if some errors are still present. Thanks.

**Closed by AlessandroZ** 2018-02-15 14:16 UTC
