### ISSUE TITLE
use current user password to decrypt without admin access or use 32bit python on 64bit system.

### ISSUE THREAD

**Issue by byehack** [AlessandroZ/LaZagne#439] opened 2019-11-25 17:07 UTC
see https://www.nirsoft.net/utils/credentials_file_view.html

we can use current user password to decrypt windows vaults and credfiles without admin access or run python 32bit in 64bit systems.

also in mimikatz we can decrypt CRED_TYPE_DOMAIN_PASSWORD with "/password:XXX". 
see [here](https://github.com/gentilkiwi/mimikatz/wiki/howto-~-credential-manager-saved-credentials) and an example at [here](http://harmj4.rssing.com/chan-30881824/latest.php)

**Comment by byehack** [comment] 2019-11-28 17:42
example:

**Comment by AlessandroZ** [comment] 2019-12-02 10:29
Hi @byehack, 

You have different ways to get passwords stored on the credential files: 
- You have the windows session password: you can pass it to lazagne as a parameter
- You are able to read the windows passwords from lsass process
- Some credentials are readable calling the Windows API. 

Lazagne does the same as mimikatz concerning these points.

**Comment by byehack** [comment] 2019-12-02 17:04
> * You have the windows session password: you can pass it to lazagne as a parameter

i use this: lazagne.exe all -password but still not working.



> Lazagne does the same as mimikatz concerning these points.

are you sure?

**Comment by AlessandroZ** [comment] 2019-12-03 10:00
Please try -password using python 2.7. I have done many tests and it worked. Check using the verbose mode to see if the password entered is well tested with the masterkey files. 

Python 3 needs is supported but still need more tests right now. 

Concerning mimikatz, it cannot retrieved your credentials files without your windows session password or from your masterkey fond.

**Comment by byehack** [comment] 2019-12-03 10:06
> Please try -password using python 2.7. I have done many tests and it worked. Check using the verbose mode to see if the password entered is well tested with the masterkey files.


i using your released version in admin mode with `-password MYPASS` and not working

**Comment by AlessandroZ** [comment] 2019-12-03 10:40
I will take a look but right now it's complicated for me.

**Comment by byehack** [comment] 2019-12-10 14:46
i tested in multiple systems but still not works!

**Comment by MyLoginOnGitHub** [comment] 2019-12-29 09:34
@AlessandroZ states that this feature works in python2. Let's assume that he is right :-)

First, as @AlessandroZ clarified, LaZagne tries to decrypt Vault with user's password in module _vaultfiles.py_.
Second, in https://github.com/AlessandroZ/LaZagne/pull/451#issuecomment-569441746 you provided result of execution on python 3.8.0. There is exception in _vaultfiles_. I think, this is not a coincidence :-)

I am sure, that the problem is that you use python3, not python2. Me to :-). As @AlessandroZ said, this code is not fully compatible with python3. Exact this exception occurres because _self.attributes_num_ is float, not int in https://github.com/AlessandroZ/LaZagne/blob/54d5d9ced03b0b8c3bff509b4dd1bb63b6eddf97/Windows/lazagne/config/DPAPI/vault.py#L205. This caused by difference in result of devide operator in python2 and python3. 

Sorry, I am not familiar with windows-domains, so I really do not want to setup domain infrastructure to test this issue. I am sure this is overkill. Lets try to solve this issue like this: I created branch https://github.com/MyLoginOnGitHub/LaZagne/tree/try-to-help-byehack. Follow this branch, try to run it on your machine with domain and post results here. I've already tried to solve this exception, but other exceptions could be occurred.

**Comment by MyLoginOnGitHub** [comment] 2019-12-29 10:25
@byehack, I've created issue in my fork. Post your results here so as not to make long conversations here

**Comment by byehack** [comment] 2019-12-29 14:03
> @byehack, I've created issue in my fork. Post your results here so as not to make long conversations here
> [MyLoginOnGitHub#4](https://github.com/MyLoginOnGitHub/LaZagne/issues/4)

ok. but here is still open! when the problem solved. i close this issue.

Continue in [MyLoginOnGitHub#4](https://github.com/MyLoginOnGitHub/LaZagne/issues/4)

**Comment by AlessandroZ** [comment] 2020-01-03 14:49
Vault files decryption are ok now, so I close this issue.

**Closed by AlessandroZ** 2020-01-03 14:49 UTC
