### ISSUE TITLE
make it on the most recent pyton

### ISSUE THREAD

**Issue by illbury** [AlessandroZ/LaZagne#244] opened 2018-07-05 12:31 UTC

**Comment by KiUserExceptionDispatcher** [comment] 2018-09-10 12:57
What for?

**Comment by q2dg** [comment] 2019-01-20 22:56
Because Python2 will die. That's all.
On the other side, it's duplicate of https://github.com/AlessandroZ/LaZagne/issues/324

**Comment by AlessandroZ** [comment] 2019-02-18 17:17
I close the issue to let only this one #324

**Closed by AlessandroZ** 2019-02-18 17:17 UTC
