### ISSUE TITLE
can not run on windows 2003 R2

### ISSUE THREAD

**Issue by sincoder** [AlessandroZ/LaZagne#60] opened 2016-07-03 10:17 UTC
in a fresh install windows 2003 R2  vm , where run the last release ,I got 
C:\Documents and Settings\Administrator\桌面\Windows>laZagne.exe all
Traceback (most recent call last):
  File "laZagne.py", line 17, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 389, in load_module
  File "site-packages\psutil\__init__.py", line 124, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 389, in load_module
  File "site-packages\psutil\_pswindows.py", line 15, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 546, in load_module
ImportError: DLL load failed: 找不到指定的程序。
Failed to execute script laZagne

maybe  some dll file not find

**Comment by AlessandroZ** [comment] 2016-07-03 11:15
Hi, 
Could you try to execute the older version of LaZagne: https://github.com/AlessandroZ/LaZagne/releases/tag/1.1

I want to understand if the problem is from psutil or another one. The older version did not use the psutil package. Thank you !

**Comment by sincoder** [comment] 2016-07-04 21:26
when run  the older version ,i got almost the same error:
C:\>laZagne.exe --ver
Traceback (most recent call last):
  File "<string>", line 20, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_import
ers.py", line 276, in load_module
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\config.manage
Modules", line 3, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_import
ers.py", line 276, in load_module
  File "C:\Users\tuquo\Desktop\LaZagne\build\LaZagne\out00-PYZ.pyz\softwares.bro
wsers.chrome", line 3, in <module>
  File "C:\Users\tuquo\Desktop\pyinstaller-develop\PyInstaller\loader\pyi_import
ers.py", line 420, in load_module
ImportError: DLL load failed: 找不到指定的程序。

**Comment by AlessandroZ** [comment] 2016-07-10 16:04
I don't know the problem because I cannot reproduce the problem. Maybe, it misses the VC Redistributable on the system. It could be the problem. I had this problem on old system (XP for example). I will try to check on a Server 2003.

**Comment by DLX23** [comment] 2016-07-22 09:26
Same Problem here on win XP:
Traceback (most recent call last):
  File "laZagne.py", line 17, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 389, in load_module
  File "site-packages\psutil\__init__.py", line 124, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 389, in load_module
  File "site-packages\psutil\_pswindows.py", line 15, in <module>
  File "C:\Users\joe\Desktop\pyinstaller-develop\PyInstaller\loader\pyimod03_imp
orters.py", line 546, in load_module
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
Failed to execute script laZagne

**Comment by 0E800** [comment] 2016-07-22 15:05
Possible solution: (translate site)

http://www.jianshu.com/p/2b25d7bf18c5

How I found the solution:
Google search: "DLL load failed: 找不到指定的程序"


Help your developer, do some initial legwork. #ß

**Comment by AlessandroZ** [comment] 2016-08-01 09:19
It is not as easy as it looks. I don't think, your solution will work because I never use Oracle component on the tool, so adding an Oracle dll on the binary will not change anything. I think the problem is from old version of Microsoft who needs the Visual C++ Redistributable (https://www.microsoft.com/en-us/download/details.aspx?id=30679). 
I hope to find a solution, I tried many things without success.

**Comment by AlessandroZ** [comment] 2016-09-11 14:31
I will close this issue. 
Another solution will be to use the pupy project (https://github.com/n1nj4sec/pupy) to launch the module lazagne. The python code is interpreted on the client session without writing any files on the disk. So it should bypass this known issue with pyinstaller.

**Closed by AlessandroZ** 2016-09-11 14:31 UTC
Labels: cannot reproduce
