### ISSUE TITLE
see traceback

### ISSUE THREAD

**Issue by KiUserExceptionDispatcher** [AlessandroZ/LaZagne#316] opened 2018-10-24 13:10 UTC
Hello. I'm sorry I can't reproduce this case but once time I had such error:

```
  File "\lazagne\config\run.py", line 169, in run_lazagne
  File "\lazagne\config\dpapi_structure.py", line 156, in __init__
  File "\lazagne\softwares\windows\lsa_secrets.py", line 25, in run
  File "\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 185, in get_file_secrets
  File "\lazagne\softwares\windows\creddump7\win32\lsasecrets.py", line 146, in get_secrets
  File "\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 112, in get_bootkey
  File "\lazagne\softwares\windows\creddump7\win32\hashdump.py", line 102, in find_control_set
  File "\lazagne\softwares\windows\creddump7\win32\rawreg.py", line 40, in open_key
  File "\lazagne\softwares\windows\creddump7\win32\rawreg.py", line 52, in subkeys
  File "\lazagne\softwares\windows\creddump7\newobj.py", line 107, in __getattribute__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

7 Pro SP1 x64
Python 2.7.15 x86
Ran as SYSTEM.

**Comment by plonibarploni** [comment] 2018-11-20 02:46
Isn't this the same as #295?

**Comment by AlessandroZ** [comment] 2019-04-11 15:45
@KiUserExceptionDispatcher, are you able to reproduce this error ? Because I can't and I don't know where the error occurs (where the concatenation is done). 

Thanks.

**Comment by AlessandroZ** [comment] 2019-04-16 15:32
I close this issue, if you have another issue like that open it again. I cannot reproduce it. Sorry.

**Closed by AlessandroZ** 2019-04-16 15:32 UTC
